# Generated by Django 5.1.2 on 2024-11-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together=set(),
        ),
    ]
